################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/bjvyhb/OneDrive\ -\ PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/asserts.c \
C:/Users/bjvyhb/OneDrive\ -\ PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/backdoor.c \
C:/Users/bjvyhb/OneDrive\ -\ PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/boot.c \
C:/Users/bjvyhb/OneDrive\ -\ PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/com.c \
C:/Users/bjvyhb/OneDrive\ -\ PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/cop.c \
C:/Users/bjvyhb/OneDrive\ -\ PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/file.c \
C:/Users/bjvyhb/OneDrive\ -\ PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/net.c \
C:/Users/bjvyhb/OneDrive\ -\ PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/xcp.c 

OBJS += \
./Loader/asserts.o \
./Loader/backdoor.o \
./Loader/boot.o \
./Loader/com.o \
./Loader/cop.o \
./Loader/file.o \
./Loader/net.o \
./Loader/xcp.o 

C_DEPS += \
./Loader/asserts.d \
./Loader/backdoor.d \
./Loader/boot.d \
./Loader/com.d \
./Loader/cop.d \
./Loader/file.d \
./Loader/net.d \
./Loader/xcp.d 


# Each subdirectory must supply rules for building sources it contributes
Loader/asserts.o: C:/Users/bjvyhb/OneDrive\ -\ PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/asserts.c Loader/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32F407xx -c -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Library/FatFS" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/ARMCM4_STM32F4" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/third_party/fatfs/src" -I../Core/Inc -I../App -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Library/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/USB_DEVICE/App" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/USB_DEVICE/Target" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Loader/backdoor.o: C:/Users/bjvyhb/OneDrive\ -\ PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/backdoor.c Loader/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32F407xx -c -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Library/FatFS" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/ARMCM4_STM32F4" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/third_party/fatfs/src" -I../Core/Inc -I../App -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Library/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/USB_DEVICE/App" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/USB_DEVICE/Target" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Loader/boot.o: C:/Users/bjvyhb/OneDrive\ -\ PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/boot.c Loader/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32F407xx -c -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Library/FatFS" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/ARMCM4_STM32F4" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/third_party/fatfs/src" -I../Core/Inc -I../App -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Library/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/USB_DEVICE/App" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/USB_DEVICE/Target" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Loader/com.o: C:/Users/bjvyhb/OneDrive\ -\ PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/com.c Loader/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32F407xx -c -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Library/FatFS" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/ARMCM4_STM32F4" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/third_party/fatfs/src" -I../Core/Inc -I../App -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Library/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/USB_DEVICE/App" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/USB_DEVICE/Target" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Loader/cop.o: C:/Users/bjvyhb/OneDrive\ -\ PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/cop.c Loader/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32F407xx -c -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Library/FatFS" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/ARMCM4_STM32F4" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/third_party/fatfs/src" -I../Core/Inc -I../App -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Library/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/USB_DEVICE/App" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/USB_DEVICE/Target" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Loader/file.o: C:/Users/bjvyhb/OneDrive\ -\ PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/file.c Loader/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32F407xx -c -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Library/FatFS" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/ARMCM4_STM32F4" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/third_party/fatfs/src" -I../Core/Inc -I../App -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Library/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/USB_DEVICE/App" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/USB_DEVICE/Target" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Loader/net.o: C:/Users/bjvyhb/OneDrive\ -\ PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/net.c Loader/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32F407xx -c -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Library/FatFS" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/ARMCM4_STM32F4" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/third_party/fatfs/src" -I../Core/Inc -I../App -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Library/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/USB_DEVICE/App" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/USB_DEVICE/Target" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Loader/xcp.o: C:/Users/bjvyhb/OneDrive\ -\ PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/xcp.c Loader/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32F407xx -c -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Library/FatFS" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/ARMCM4_STM32F4" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/openBLT/openblt_v011600/Target/Source/third_party/fatfs/src" -I../Core/Inc -I../App -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/Library/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/USB_DEVICE/App" -I"C:/Users/bjvyhb/OneDrive - PHINIA/Desktop/FastBit/My_Boot_STM32F407/My_openblt/USB_DEVICE/Target" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Loader

clean-Loader:
	-$(RM) ./Loader/asserts.cyclo ./Loader/asserts.d ./Loader/asserts.o ./Loader/asserts.su ./Loader/backdoor.cyclo ./Loader/backdoor.d ./Loader/backdoor.o ./Loader/backdoor.su ./Loader/boot.cyclo ./Loader/boot.d ./Loader/boot.o ./Loader/boot.su ./Loader/com.cyclo ./Loader/com.d ./Loader/com.o ./Loader/com.su ./Loader/cop.cyclo ./Loader/cop.d ./Loader/cop.o ./Loader/cop.su ./Loader/file.cyclo ./Loader/file.d ./Loader/file.o ./Loader/file.su ./Loader/net.cyclo ./Loader/net.d ./Loader/net.o ./Loader/net.su ./Loader/xcp.cyclo ./Loader/xcp.d ./Loader/xcp.o ./Loader/xcp.su

.PHONY: clean-Loader

